from __future__ import annotations
from src.paths import *
from src.bounding_box import BoundingBox, calculate_iou_corners
from src.settings import load_settings, save_settings
from src.model_utils import get_latest_weights, collect_images
from src.theme import *


from typing import *
from pathlib import Path
import tkinter as tk
from tkinter import ttk, messagebox, filedialog
from PIL import Image, ImageTk, ImageDraw


class ActiveLearningMixin:
    def _discard_recount(self):
        """Remove all boxes generated by the last auto-recount or restore backup."""
        if hasattr(self, 'boxes_backup') and self.boxes_backup is not None:
            self.boxes = list(self.boxes_backup)
            self.boxes_backup = None
            self._redraw_boxes()
            self._save_labels()
            self._update_ui()
            self.status.config(text=" ↩ Restored previous boxes.")
            return

        if not self.boxes: return
        original_len = len(self.boxes)
        self.boxes = [b for b in self.boxes if not getattr(b, 'is_auto', False)]
        removed = original_len - len(self.boxes)
        if removed > 0:
            self._redraw_boxes()
            self._save_labels()
            self._update_ui()
            self.status.config(text=f" Discarded {removed} auto-recounted boxes.")

    def _regional_recount(self, nx1, ny1, nx2, ny2):
        """Run YOLO only in the region [nx1, nx2] x [ny1, ny2] by cropping the image."""
        if not hasattr(self, 'orig_pil_img') or not self.orig_pil_img or not self.image_paths: return

        self.boxes_backup = list(self.boxes)
        force = getattr(self, 'force_recount_var', None) and self.force_recount_var.get()
        if force:
            # Delete existing boxes whose centers fall inside this region
            kept_boxes = []
            removed = 0
            for box in self.boxes:
                if nx1 <= box.x_center <= nx2 and ny1 <= box.y_center <= ny2:
                    removed += 1
                else:
                    kept_boxes.append(box)
            self.boxes = kept_boxes
            if removed > 0:
                self.status.config(text=f" Removed {removed} old boxes.")
                self.root.update()

        try:
            conf_val = float(self.conf_entry.get().replace(',', '.'))
        except ValueError:
            messagebox.showerror("Error", "Invalid confidence value")
            return
            
        try:
            iou_val = float(self.iou_entry.get().replace(',', '.'))
        except ValueError:
            messagebox.showerror("Error", "Invalid IoU value")
            return
            
        selected_model = getattr(self, 'model_combo', None)
        if selected_model:
            selected_model = selected_model.get()
        else:
            selected_model = "None"

        if selected_model == "None":
            messagebox.showerror("Error", "No model selected.")
            return

        if self.yolo_model is not None and getattr(self, 'loaded_model_name', None) != selected_model:
            self.yolo_model = None
            self.sahi_model = None

        if self.yolo_model is None:
            self.status.config(text=f" Loading YOLO model: {selected_model}...")
            self.root.update()
            try:
                from ultralytics import YOLO
                model_path = PROJECT_ROOT / "runs" / "detect" / selected_model / "weights" / "best.pt"
                if not model_path.exists():
                    messagebox.showerror("Error", f"Could not find a trained best.pt model in {model_path}!")
                    self.status.config(text=" Model load failed")
                    return
                self.yolo_model = YOLO(model_path)
                try:
                    from sahi import AutoDetectionModel
                    self.sahi_model = AutoDetectionModel.from_pretrained(
                        model_type="yolov8", model_path=str(model_path), confidence_threshold=conf_val, device="cuda:0"
                    )
                except Exception:
                    self.sahi_model = None
                self.loaded_model_name = selected_model
            except Exception as e:
                messagebox.showerror("Error", f"Failed to load YOLO: {e}")
                self.status.config(text=" Model load failed")
                return

        self.status.config(text=f" Running regional inference...")
        self.root.update()
        
        # Crop the image to the selected region
        img_path = str(self.image_paths[self.current_idx])
        img_bgr = cv2.imread(img_path)
        if img_bgr is None:
            return
            
        img_h, img_w = img_bgr.shape[:2]
        
        px1 = int(nx1 * img_w)
        py1 = int(ny1 * img_h)
        px2 = int(nx2 * img_w)
        py2 = int(ny2 * img_h)
        
        px1 = max(0, min(img_w, px1))
        py1 = max(0, min(img_h, py1))
        px2 = max(0, min(img_w, px2))
        py2 = max(0, min(img_h, py2))
        
        if px2 <= px1 or py2 <= py1:
            return
            
        roi = img_bgr[py1:py2, px1:px2]
        
        use_sahi = hasattr(self, 'use_sahi_var') and self.use_sahi_var.get()
        new_boxes = []
        roi_w = px2 - px1
        roi_h = py2 - py1
        
        if use_sahi and getattr(self, 'sahi_model', None) is not None:
            self.sahi_model.confidence_threshold = conf_val
            from sahi.predict import get_sliced_prediction
            roi_rgb = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)
            results = get_sliced_prediction(
                roi_rgb,
                self.sahi_model,
                slice_height=512,
                slice_width=512,
                overlap_height_ratio=0.2,
                overlap_width_ratio=0.2,
                verbose=0
            )
            
            if results.object_prediction_list:
                for pred in results.object_prediction_list:
                    bbox = pred.bbox
                    xc_roi = (bbox.minx + bbox.maxx) / 2.0 / roi_w
                    yc_roi = (bbox.miny + bbox.maxy) / 2.0 / roi_h
                    w_roi = (bbox.maxx - bbox.minx) / roi_w
                    h_roi = (bbox.maxy - bbox.miny) / roi_h
                    
                    xc_px = px1 + (xc_roi * roi_w)
                    yc_px = py1 + (yc_roi * roi_h)
                    w_px = w_roi * roi_w
                    h_px = h_roi * roi_h
                    
                    xc = xc_px / img_w
                    yc = yc_px / img_h
                    w = w_px / img_w
                    h = h_px / img_h
                    new_boxes.append(BoundingBox(float(xc), float(yc), float(w), float(h), class_id=0, is_auto=True))
        else:
            results = self.yolo_model.predict(
                source=roi,
                conf=conf_val,
                iou=iou_val,
                agnostic_nms=True,
                imgsz=1024,
                max_det=5000,
                device="0",
                verbose=False
            )
            
            if results and results[0].boxes:
                for box_data in results[0].boxes:
                    xywhn = box_data.xywhn[0].cpu().numpy()
                    xc_roi, yc_roi, w_roi, h_roi = xywhn
                    
                    xc_px = px1 + (xc_roi * roi_w)
                    yc_px = py1 + (yc_roi * roi_h)
                    w_px = w_roi * roi_w
                    h_px = h_roi * roi_h
                    
                    xc = xc_px / img_w
                    yc = yc_px / img_h
                    w = w_px / img_w
                    h = h_px / img_h
                    new_boxes.append(BoundingBox(float(xc), float(yc), float(w), float(h), class_id=0, is_auto=True))
                    
        if not new_boxes:
            return
            
        new_count = 0
        for new_box in new_boxes:
            # Check overlap against all existing boxes
            is_overlap = False
            for exist_box in self.boxes:
                if exist_box.iou(new_box) > 0.25:
                    is_overlap = True
                    break
                    
            if not is_overlap:
                if getattr(self, 'auto_snap', None) and self.auto_snap.get():
                    self._snap_single_box(new_box)
                self.boxes.append(new_box)
                new_count += 1
                
        self.status.config(text=f" Regional recount: Added {new_count} pollen grains.")


    def _auto_recount(self):
        """Lazy load YOLO, run inference, and add non-overlapping boxes."""
        if not hasattr(self, 'orig_pil_img') or not self.orig_pil_img or not self.image_paths: return
        
        try:
            conf_val = float(self.conf_entry.get().replace(',', '.'))
        except ValueError:
            messagebox.showerror("Error", "Invalid confidence value")
            return
            
        try:
            iou_val = float(self.iou_entry.get().replace(',', '.'))
        except ValueError:
            messagebox.showerror("Error", "Invalid IoU value")
            return
            
        selected_model = getattr(self, 'model_combo', None)
        if selected_model:
            selected_model = selected_model.get()
        else:
            selected_model = "None"

        if selected_model == "None":
            messagebox.showerror("Error", "No model selected.")
            return

        if self.yolo_model is not None and getattr(self, 'loaded_model_name', None) != selected_model:
            print(f"[INFO] Switching model to {selected_model}")
            self.yolo_model = None
            self.sahi_model = None

        if self.yolo_model is None:
            self.status.config(text=f" Loading YOLO model: {selected_model}...")
            self.root.update()
            try:
                from ultralytics import YOLO
                
                model_path = PROJECT_ROOT / "runs" / "detect" / selected_model / "weights" / "best.pt"
                
                if not model_path.exists():
                    messagebox.showerror("Error", f"Could not find a trained best.pt model in {model_path}!")
                    self.status.config(text=" Model load failed")
                    return
                    
                print(f"[INFO] Lazy-loading model from: {model_path}")
                self.yolo_model = YOLO(model_path)
                
                try:
                    from sahi import AutoDetectionModel
                    self.sahi_model = AutoDetectionModel.from_pretrained(
                        model_type="yolov8",
                        model_path=str(model_path),
                        confidence_threshold=conf_val,
                        device="cuda:0",
                    )
                except Exception as e:
                    print(f"[WARN] Failed to load SAHI model: {e}")
                    self.sahi_model = None
                    
                self.loaded_model_name = selected_model
            except Exception as e:
                messagebox.showerror("Error", f"Failed to load YOLO: {e}")
                self.status.config(text=" Model load failed")
                return
        
        img_path = str(self.image_paths[self.current_idx])
        use_sahi = hasattr(self, 'use_sahi_var') and self.use_sahi_var.get()
        new_boxes = []
        
        self.boxes_backup = list(self.boxes)
        force = getattr(self, 'force_recount_var', None) and self.force_recount_var.get()
        if force:
            self.boxes.clear()
            self._redraw_boxes()
            self.root.update()
            
        if use_sahi and getattr(self, 'sahi_model', None) is not None:
            self.status.config(text=f" Running SAHI inference at conf {conf_val}...")
            self.root.update()
            self.sahi_model.confidence_threshold = conf_val
            
            from sahi.predict import get_sliced_prediction
            results = get_sliced_prediction(
                img_path,
                self.sahi_model,
                slice_height=512,
                slice_width=512,
                overlap_height_ratio=0.2,
                overlap_width_ratio=0.2,
                verbose=0
            )
            
            if results.object_prediction_list:
                img_w, img_h = self.orig_pil_img.size
                for pred in results.object_prediction_list:
                    bbox = pred.bbox
                    xc = (bbox.minx + bbox.maxx) / 2.0 / img_w
                    yc = (bbox.miny + bbox.maxy) / 2.0 / img_h
                    w = (bbox.maxx - bbox.minx) / img_w
                    h = (bbox.maxy - bbox.miny) / img_h
                    new_boxes.append(BoundingBox(float(xc), float(yc), float(w), float(h), class_id=0, is_auto=True))
        else:
            self.status.config(text=f" Running inference at conf {conf_val}...")
            self.root.update()
            
            results = self.yolo_model.predict(
                source=img_path,
                conf=conf_val,
                iou=iou_val,
                agnostic_nms=True,
                imgsz=1024,
                max_det=5000,
                device="0", 
                verbose=False
            )
            
            if results and results[0].boxes:
                for box_data in results[0].boxes:
                    xywhn = box_data.xywhn[0].cpu().numpy()
                    xc, yc, w, h = xywhn
                    new_boxes.append(BoundingBox(float(xc), float(yc), float(w), float(h), class_id=0, is_auto=True))
                    
        if not new_boxes:
            self.status.config(text=" No new boxes found.")
            return

        new_count = 0
        for new_box in new_boxes:
            # Filter: Check overlap against all existing boxes
            is_overlap = False
            for exist_box in self.boxes:
                if exist_box.iou(new_box) > 0.25:
                    is_overlap = True
                    break
                    
            if not is_overlap:
                if getattr(self, 'auto_snap', None) and self.auto_snap.get():
                    self._snap_single_box(new_box)
                self.boxes.append(new_box)
                new_count += 1
                
        self._redraw_boxes()
        self._save_labels()
        self._update_ui()
        self.status.config(text=f" Auto-recount: Added {new_count} missing pollen grains.")

