"""YOLO-format bounding box and IoU utilities.

Shared by annotate.py, compare_val.py, inference.py, and clean_duplicate_points.py.

Usage:
    from src.bounding_box import BoundingBox, calculate_iou
"""

from __future__ import annotations
from typing import Optional


class BoundingBox:
    """Single YOLO-format bounding box (normalized 0-1 coordinates).

    Attributes:
        x_center, y_center: box center (normalized).
        w, h: box width/height (normalized).
        class_id: integer class label (default 0 = pollen).
        is_auto: True if generated by AI recount, False if drawn by human.
    """

    def __init__(
        self,
        x_center: float,
        y_center: float,
        w: float,
        h: float,
        class_id: int = 0,
        is_auto: bool = False,
    ):
        self.x_center = x_center
        self.y_center = y_center
        self.w = w
        self.h = h
        self.class_id = class_id
        self.is_auto = is_auto

    def to_yolo_line(self) -> str:
        """Serialize to a single YOLO label line. Example: '0 0.512000 0.340000 0.080000 0.090000'"""
        return f"{self.class_id} {self.x_center:.6f} {self.y_center:.6f} {self.w:.6f} {self.h:.6f}"

    @classmethod
    def from_yolo_line(cls, line: str) -> Optional["BoundingBox"]:
        """Parse a YOLO label line. Returns None on malformed input."""
        parts = line.strip().split()
        if len(parts) != 5:
            return None
        try:
            cid, xc, yc, w, h = int(parts[0]), float(parts[1]), float(parts[2]), float(parts[3]), float(parts[4])
            return cls(xc, yc, w, h, cid)
        except ValueError:
            return None

    def to_pixel(self, img_w: int, img_h: int) -> tuple[int, int, int, int]:
        """Convert to pixel coords (x1, y1, x2, y2). Example: box.to_pixel(1024, 768)"""
        px = self.x_center * img_w
        py = self.y_center * img_h
        pw = self.w * img_w
        ph = self.h * img_h
        return (
            int(px - pw / 2),
            int(py - ph / 2),
            int(px + pw / 2),
            int(py + ph / 2),
        )

    def iou(self, other: "BoundingBox") -> float:
        """Intersection over Union with another normalized box."""
        x_left  = max(self.x_center - self.w / 2, other.x_center - other.w / 2)
        y_top   = max(self.y_center - self.h / 2, other.y_center - other.h / 2)
        x_right = min(self.x_center + self.w / 2, other.x_center + other.w / 2)
        y_bottom = min(self.y_center + self.h / 2, other.y_center + other.h / 2)

        if x_right < x_left or y_bottom < y_top:
            return 0.0

        intersection = (x_right - x_left) * (y_bottom - y_top)
        area1 = self.w * self.h
        area2 = other.w * other.h
        return intersection / (area1 + area2 - intersection)


def calculate_iou(box_a: tuple, box_b: tuple) -> float:
    """IoU for pixel-coordinate boxes in (cx, cy, w, h) format.

    Used by clean_duplicate_points and compare_val for raw coordinate comparisons.

    Args:
        box_a: (cx, cy, w, h) — center-x, center-y, width, height.
        box_b: same format.

    Returns:
        IoU value between 0.0 and 1.0.
    """
    cx1, cy1, w1, h1 = box_a
    cx2, cy2, w2, h2 = box_b

    # Convert to corner format (x1, y1, x2, y2)
    x1A, y1A = cx1 - w1 / 2, cy1 - h1 / 2
    x2A, y2A = cx1 + w1 / 2, cy1 + h1 / 2
    x1B, y1B = cx2 - w2 / 2, cy2 - h2 / 2
    x2B, y2B = cx2 + w2 / 2, cy2 + h2 / 2

    xA = max(x1A, x1B)
    yA = max(y1A, y1B)
    xB = min(x2A, x2B)
    yB = min(y2A, y2B)

    inter = max(0, xB - xA) * max(0, yB - yA)
    if inter == 0:
        return 0.0

    area_a = (x2A - x1A) * (y2A - y1A)
    area_b = (x2B - x1B) * (y2B - y1B)
    return inter / float(area_a + area_b - inter)


def calculate_iou_corners(box_a: list, box_b: list) -> float:
    """IoU for pixel-coordinate boxes in [x1, y1, x2, y2] corner format.

    Used by compare_val's report generator for matching human vs model boxes.
    """
    xA = max(box_a[0], box_b[0])
    yA = max(box_a[1], box_b[1])
    xB = min(box_a[2], box_b[2])
    yB = min(box_a[3], box_b[3])

    inter = max(0, xB - xA) * max(0, yB - yA)
    if inter == 0:
        return 0.0

    area_a = (box_a[2] - box_a[0]) * (box_a[3] - box_a[1])
    area_b = (box_b[2] - box_b[0]) * (box_b[3] - box_b[1])
    return inter / float(area_a + area_b - inter)
